# action.yml
name: 'qt_docker_action'
description: 'runs arbitrary commands inside a docker container that has qmake et al'
inputs: 
  project_file:
    required: true
  executable:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.project_file }}
      ${{ inputs.executable }}
