name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: mobile_bungalow/qt_docker_action@valpha
  test_actual:
    runs-on: ubuntu-latest
    steps:
    - use: mobile_bungalow/qt_docker_action@valpha
        with:
          command: "echo malto benne! && qmake"

